### ISSUE TITLE
Add support for adding service_data in grid item actions

### ISSUE THREAD

**Issue by nielsrowinbik** [nielsrowinbik/google-home-assistant#15]
Currently service calls are supported, and we correctly pass the `entity_id`, however more control would be useful. For instance, I would like to call a script that increases the temperature for one hour right from the thermostat's grid item:

```yaml
type: custom:google-home-grid-item
entity: climate.living_room
icon: /local/images/thermostat.svg
actions:
  - label: Heat 1hr
    service: script.turn_on
    service_data:
      entity_id: script.increase_heating
```

**To do**
- [x] Allow for `service_data` option
- [ ] <s>Provide `entity_id` if unspecified in `service_data`, but allow `entity_id` field in `service_data` to override the value we set</s>
- [x] Call specified service with specified data
